# Generated by Django 5.0.7 on 2025-08-28 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_sku', models.CharField(blank=True, help_text='SKU interno opcional', max_length=64, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('name', 'base_sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('MPN', 'MPN'), ('UPC_EAN', 'UPC/EAN'), ('SKU_ALT', 'SKU alterno')], max_length=16)),
                ('value', models.CharField(db_index=True, max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='catalogo.product')),
            ],
            options={
                'unique_together': {('id_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_value', models.CharField(help_text='Valor exacto encontrado en el catálogo del proveedor', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_items', to='catalogo.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogo.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'identifier_value')},
            },
        ),
    ]
