# Generated by Django 5.0.7 on 2025-08-24 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('mpn', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gtin', models.CharField(blank=True, db_index=True, max_length=20)),
                ('socket', models.CharField(blank=True, max_length=80)),
                ('short_description', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed_rows', models.IntegerField(default=0)),
                ('created_links', models.IntegerField(default=0)),
                ('updated_links', models.IntegerField(default=0)),
                ('created_products', models.IntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('mpn', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gtin', models.CharField(blank=True, db_index=True, max_length=20)),
                ('name_in_feed', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='MXN', max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('availability', models.CharField(blank=True, max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='catalogo.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'gtin'), ('supplier', 'mpn'), ('supplier', 'supplier_sku')},
            },
        ),
    ]
