# Generated by Django 5.0.7 on 2025-08-24 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjob',
            options={'verbose_name': 'Importación de catálogo', 'verbose_name_plural': 'Importaciones de catálogos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={'verbose_name': 'Producto de proveedor', 'verbose_name_plural': 'Productos de proveedores'},
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created_links',
            field=models.IntegerField(default=0, verbose_name='Vínculos creados'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created_products',
            field=models.IntegerField(default=0, verbose_name='Productos nuevos'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='Nombre de archivo'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado en'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='processed_rows',
            field=models.IntegerField(default=0, verbose_name='Filas procesadas'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Iniciado en'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='updated_links',
            field=models.IntegerField(default=0, verbose_name='Vínculos actualizados'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Código GTIN/UPC/EAN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Número de parte (MPN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=280, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='product',
            name='socket',
            field=models.CharField(blank=True, max_length=80, verbose_name='Socket'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuración'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='availability',
            field=models.CharField(blank=True, max_length=60, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='currency',
            field=models.CharField(default='MXN', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='GTIN/UPC/EAN'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='mpn',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Número de parte (MPN)'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='name_in_feed',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre en catálogo'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='catalogo.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Existencias'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_sku',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='SKU del proveedor'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
    ]
